# Generated by Django 6.1.1 on 2026-10-03 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EntreprisesApp', '0002_rename_matricul_fiscale_entreprise_matricule_fiscal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=30, unique=True)),
                ('type_vehicule', models.CharField(choices=[('camionette', 'Camionette'), ('fourgon', 'Fourgon'), ('camion_porteur', 'Camion_porteur'), ('semi_remorque', 'Semi_remorque')], max_length=100)),
                ('capacite_kg', models.PositiveIntegerField()),
                ('disponibilite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='EntreprisesApp.entreprise')),
            ],
        ),
    ]
