# Generated by Django 6.1.1 on 2026-10-05 14:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehiculesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='capacite_kg',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'La capacité doit etre sup à 0 kg')]),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='disponibilite',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='immatriculation',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='type_vehicule',
            field=models.CharField(choices=[('camionette', 'Camionette'), ('fourgon', 'Fourgon'), ('camion_porteur', 'Camion_porteur'), ('semi_remorque', 'Semi_remorque')], max_length=50),
        ),
    ]
