# Generated by Django 6.1.1 on 2026-10-03 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EntreprisesApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entreprise',
            old_name='matricul_fiscale',
            new_name='matricule_fiscal',
        ),
        migrations.RenameField(
            model_name='entreprise',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='utilisateur',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
