# Generated by Django 6.1.1 on 2026-10-05 14:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntreprisesApp', '0002_rename_matricul_fiscale_entreprise_matricule_fiscal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='adress',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(20, "l'adress doit contenir au min 2 caracteres")]),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='matricule_fiscal',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Format non conforme', regex='^\\d{7}[/ -]?[A-Za-z][/ -]?[ABDNPEabdnpe][/ -]?[MPCNEmpcne][/ -]\\d{3}$')]),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('chargeur', 'Chargeur'), ('transporteur', 'Transporteur'), ('administrateur', 'Administrateur')], default='transporteur', max_length=20),
        ),
    ]
