# Generated by Django 6.1.1 on 2026-10-03 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EntreprisesApp', '0002_rename_matricul_fiscale_entreprise_matricule_fiscal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=20, unique=True)),
                ('ville_depart', models.CharField(max_length=20)),
                ('ville_arrivee', models.CharField(max_length=20)),
                ('poids_kg', models.DecimalField(decimal_places=3, max_digits=6)),
                ('date_souhaitee', models.DateField()),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('publiee', 'Publiee'), ('attribuee', 'Attribuee'), ('en_cours', 'En_cours'), ('livree', 'Livree'), ('annulee', 'Anunulee')], default='publiee', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expidations', to='EntreprisesApp.entreprise')),
            ],
        ),
    ]
